### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by wnzhyee** [bearpaw/pose-attention#10]
I see that in train.sh, it use 4x12G GPUs for training, but i only have one 12G GPU(1080 Ti), so how can i reduce the GPU cost?

i try change '-nGPU 4' to '-nGPU 1', and add '-trainBatch 4' in train.sh, but it seems doesn't  work because the model 'converting the model to CUDA' again and again, just like:

![_2017-11-07_21-39-01](https://user-images.githubusercontent.com/28294770/32496417-17e84388-c404-11e7-8730-1eebe998d5b1.png)

So how can i do?Thanks.

**Comment by bearpaw** [comment]
This might not be an 'out of memory' issue. We've seen this occasionally also in our experiment, and we don't know the reason. 

You can simply kill the program and rerun it.

**Comment by larklili** [comment]
@wnzhyee i have only one 12GB gpu too.what's your solution?could you please tell me the method?:)thanks
