### ISSUE TITLE
A question in "pose-attention/train/models/layers/AttentionPartsCRF.lua"

### ISSUE THREAD

**Issue by y-dep** [bearpaw/pose-attention#4]
Hey, 
    I'm trying to re-implemented your method using tensorflow, while I'm not very proficient in torch. I'm quite confused about *** line 24  *** in AttentionPartsCRF.lua, does that mean just copy the same tensor     ( *** Q[itersize] ***) on its  channel  for many(*** numIn ***) times? 
    I'm quite confused about that and hope to get an reply. Thanks. @bearpaw

**Comment by yicheng-li** [comment]
@bearpaw

**Comment by bearpaw** [comment]
Hi @yicheng-li ,

`Q[itersize]` is the single-channel attention map. We need to multiply it to each channel of the features. Thus we first replicate it to the same channels as the feature maps, and then do element-wise multiplication.  

Note that there is no memory allocation or memory copy in `nn.Replicate`.

**Comment by y-dep** [comment]
Oh, get it! Thanks for your reply very much!
