### ISSUE TITLE
test error!

### ISSUE THREAD

**Issue by zilesazoyi2** [bearpaw/pose-attention#5]
Thanks for you code! could you give me some advice? thanks a lot!

sun@sunwin:~/0newcodedown/pose-attention-master/test$  qlua main.lua demo
qlua: /home/sun/torch/install/share/lua/5.1/hdf5/ffi.lua:42: Error: unable to locate HDF5 header file at /usr/local/HDF_Group/HDF5/1.8.18/include;/hdf5.h
stack traceback:
	[C]: at 0x7f6031a5bf50
	[C]: in function 'error'
	/home/sun/torch/install/share/lua/5.1/hdf5/ffi.lua:42: in function 'loadHDF5Header'
	/home/sun/torch/install/share/lua/5.1/hdf5/ffi.lua:60: in main chunk
	[C]: in function 'dofile'
	/home/sun/torch/install/share/lua/5.1/torch/init.lua:54: in function 'include'
	/home/sun/torch/install/share/lua/5.1/hdf5/init.lua:29: in main chunk
	[C]: in function 'require'
	/home/sun/0newcodedown/pose-attention-master/test/util.lua:7: in main chunk
	[C]: in function 'dofile'
	main.lua:9: in main chunk

**Comment by bearpaw** [comment]
Try to use `luarocks install hdf5` to install hdft.
