### ISSUE TITLE
Multi-Resolution Attention

### ISSUE THREAD

**Issue by wuneng** [bearpaw/pose-attention#6]
Hi,
    In your paper,multi-resolution attention maps are generated from features of different scales.But in your train script , only  original resolution generates attention map ， is it my fault?

**Comment by bearpaw** [comment]
@wuneng You are right. For simplicity, in [hg-attention.lua](https://github.com/bearpaw/pose-attention/blob/master/train/models/hg-attention.lua), we only generate attention outside the hourglass.
