### ISSUE TITLE
About the batch size and the log.

### ISSUE THREAD

**Issue by xizero00** [bearpaw/pose-attention#7]
Hi @bearpaw 
Very nice work! 
I have not found the batch size for MPII and LSP dataset in your CVPR 2017 paper.
Would you please provide your train.log valid.log for reference , the batch size for MPII and LSP dataset and the train/valid iterations per epoch for MPII and LSP dataset  in your paper.

Thank you.
Feng.

**Comment by bearpaw** [comment]
The batch size we used can be found at https://github.com/bearpaw/pose-attention/blob/master/train/opts.lua#L44-L47
