### ISSUE TITLE
test bug

### ISSUE THREAD

**Issue by cltdevelop** [bearpaw/pose-attention#8]
Great work!
Thank you for sharing this code.
I encounter a problem when I test your code named "main.lua". I input this command "qlua main.lua demo" in command of Ubuntu. The bug is as follows:

HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139704096257792:
  #000: H5F.c line 586 in H5Fopen(): interface initialization failed
    major: Function entry/exit
    minor: Unable to initialize object
  #001: H5F.c line 112 in H5F__init_pub_interface(): unable to initialize interface
    major: File accessibilty
    minor: Unable to initialize object
  #002: ../../../src/H5I.c line 344 in H5I_register_type(): invalid hash size
    major: Object atom
    minor: Out of range
qlua: /home/yzl/torch/install/share/lua/5.2/hdf5/file.lua:12: HDF5File: fileID -1 is not valid
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/home/yzl/torch/install/share/lua/5.2/hdf5/file.lua:12: in function '__init'
	/home/yzl/torch/install/share/lua/5.2/torch/init.lua:91: in function </home/yzl/torch/install/share/lua/5.2/torch/init.lua:87>
	[C]: in function 'HDF5File'
	/home/yzl/torch/install/share/lua/5.2/hdf5/file.lua:147: in function </home/yzl/torch/install/share/lua/5.2/hdf5/file.lua:145>
	(...tail calls...)
	.../AI_Challenge/skeleton/Code/pose-attention/test/util.lua:19: in function 'loadAnnotations'
	main.lua:113: in main chunk
HDF5: infinite loop closing library
      D,T,FD,P,FD,P,FD,P,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E

Thank you!

**Comment by bearpaw** [comment]
Sorry that I cannot repeat your error. Please also make sure that the h5 files are not corrupted.
