### ISSUE TITLE
Why the function 'postprocess' works?

### ISSUE THREAD

**Issue by taokong** [bearpaw/pose-attention#9]
Hi @bearpaw 
I see the function postprocess in 'test/util.lua' just add 0.25 or 0.75 of the original coods, and could give about 0.5(PCK@0.5) improvement. 

Can you explain it? Thanks in advance.

**Comment by bearpaw** [comment]
This is following https://github.com/anewell/pose-hg-train/blob/c25da4b48c74a7b314384b07e8c09a15b0343e7f/src/util/pose.lua#L78

Intuitively, it's a kind of soft-argmax: the coordinates are shifted towards the direction with more confidence (higher score).

**Comment by taokong** [comment]
@bearpaw 
Thanks for pointing out. I'm still confused about it. Why the coordinates only add values(0.25/0.75)? If the diff < 0, I think we should minus some values. 

As in [https://github.com/anewell/pose-hg-train/blob/c25da4b48c74a7b314384b07e8c09a15b0343e7f/src/util/pose.lua#L97](https://github.com/anewell/pose-hg-train/blob/c25da4b48c74a7b314384b07e8c09a15b0343e7f/src/util/pose.lua#L97). The coords also add 0.5

**Comment by taokong** [comment]
Sorry, I think I have known how it works

**Comment by Yishun99** [comment]
Hi @bearpaw ,
I can't find any invoke of function `postprocess(heatmap, p)` in util.

The line in train.lua
```lua
if postprocess then preds:sub(i,i+r.batchsize-1):copy(postprocess(set,i,output)) end
```
call `postprocess(set, idx, output)` in pose-int.lua or pose.lua.

Where is the shift post-process invoked?
